<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3system\models\base;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "sys_cron_final_point".
 *
 * @property integer $id
 * @property string $route
 * @property string $value
 * @property string $timestamp
 * @property string $aliasModel
 */
abstract class SysCronFinalPoint extends ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'sys_cron_final_point';
    }


    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return [
            [['timestamp'], 'safe'],
            [['route', 'value'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3system', 'ID'),
            'route' => Yii::t('d3system', 'Route'),
            'value' => Yii::t('d3system', 'Value'),
            'timestamp' => Yii::t('d3system', 'Timestamp'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'route' => Yii::t('d3system', 'Route'),
            'value' => Yii::t('d3system', 'Value'),
            'timestamp' => Yii::t('d3system', 'Timestamp'),
        ]);
    }




}
